$ErrorActionPreference='Stop'
$Repo='https://raw.githubusercontent.com/mikecappi22/Ultimate-prompt-creator-'
$Ref='d2c208a3680df9ce394c304f11285a74a523cd53'
$Dir=Join-Path $env:LOCALAPPDATA 'UltimatePromptCreatorMobile';$App=Join-Path $Dir 'index.html';$Backup=Join-Path $Dir ('index-before-v150-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'.html');$Bridge=Join-Path $Dir 'private-mobile-proxy-v1187.ps1';$Tmp=Join-Path $env:TEMP 'UPC-V150';$PrivateUrl='https://laptop-5efmmkr5.tail97be36.ts.net/';$Utf8NoBom=New-Object System.Text.UTF8Encoding($false)
Write-Host '=== Ultimate Prompt Creator V15 Installer ===' -ForegroundColor Cyan
Write-Host 'Product Dashboard + Quick Create + Full Backup/Restore + Platform Health + all V14.8 features.'
New-Item -ItemType Directory -Force -Path $Dir,$Tmp|Out-Null
function D([string]$n){$u="$Repo/$Ref/$n";$d=Join-Path $Tmp $n;Write-Host "  downloading $n";Invoke-WebRequest $u -OutFile $d -UseBasicParsing;if(-not(Test-Path $d)){throw "Download failed: $n"};$d}
function T([string]$p){[IO.File]::ReadAllText($p,[Text.Encoding]::UTF8)}
function Stop-B{Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" -ErrorAction SilentlyContinue|?{$_.CommandLine -match 'private-mobile-proxy-v1187\.ps1' -and $_.CommandLine -match '8765'}|%{try{Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue}catch{}}}
function Start-B{Start-Process powershell -WindowStyle Hidden -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',"`"$Bridge`"",'-AppFile',"`"$App`"",'-Port','8765')}
Write-Host 'Step 1/8 - Downloading pinned V15 components...'
$Shell=D 'private-unified-v143-shell.html';$Defaults=D 'subject-defaults-v134.js';$Vault=D 'subject-vault-v143.js';$Prefill=D 'subject-profile-paste-v143.js';$Library=D 'prompt-library-v143.js';$Composer=D 'smart-composer-v144.js';$Production=D 'production-hub-v145.js';$Ext=D 'studio-extensions-v146.js';$Cont=D 'continuity-suite-v147.js';$Batch=D 'creative-batch-v148.js';$Product=D 'product-shell-v150.js';$BridgeSrc=D 'private-mobile-proxy-v1187.ps1';$Worker=D 'db-worker-v100.js';$Gz=D 'db-v8-mobile.v93.json.gz';$Json=D 'db-v8-mobile.json';$Cam=@();1..5|%{$Cam+=D ("camera-addon-v81.part$_.txt")}
Write-Host 'Step 2/8 - Assembling V15 Product Studio...'
$html=T $Shell;$html=$html.Replace('/*__SUBJECT_DEFAULTS__*/',(T $Defaults)).Replace('/*__SUBJECT_VAULT__*/',(T $Vault)).Replace('/*__PROFILE_PREFILL__*/',(T $Prefill)).Replace('/*__PROMPT_LIBRARY__*/',(T $Library));$scripts=@($Composer,$Production,$Ext,$Cont,$Batch,$Product)|%{"<script>`r`n$(T $_)`r`n</script>"};$html=$html.Replace('</body>',(($scripts -join "`r`n")+"`r`n</body>"));$html=$html.Replace('Ultimate Prompt Creator V14.3 Unified','Ultimate Prompt Creator V15 Product Studio').Replace('V14.3 UNIFIED','V15 PRODUCT STUDIO').Replace('Subjects, Creative Director, Prompt Library and Prompt Workspace in one private app.','V15 polished creative production system with Dashboard, Subjects, Smart Build, Production, Studio+, Continuity+, Creative Batch, Director, Library and Prompt Workspace.')
foreach($m in @('V15 PRODUCT STUDIO','Ultimate Prompt Creator V15','Platform Health','Backup & Restore','Quick Create','Prompt Variations','Dialogue Builder','Batch Prompt Builder','Asset Vault','Continuity Matrix','Environment Vault','Production Studio','Smart Prompt Composer','Prompt Library')){if(-not $html.Contains($m)){throw "Candidate missing: $m"}}
foreach($bad in @('Export Photo Backup','Import Photo Backup','svPhotoInput','IndexedDB','PHOTO_DB','PHOTO_STORE','Tailscale Funnel')){if($html.Contains($bad)){throw "Disallowed legacy item: $bad"}}
$candidate=Join-Path $Tmp 'index-v150-candidate.html';[IO.File]::WriteAllText($candidate,$html,$Utf8NoBom)
Write-Host 'Step 3/8 - Backing up current page...';if(Test-Path $App){Copy-Item $App $Backup -Force}
Write-Host 'Step 4/8 - Installing local assets...';Copy-Item $BridgeSrc $Bridge -Force;Copy-Item $Worker (Join-Path $Dir 'db-worker-v100.js') -Force;Copy-Item $Gz (Join-Path $Dir 'db-v8-mobile.v93.json.gz') -Force;Copy-Item $Json (Join-Path $Dir 'db-v8-mobile.json') -Force;foreach($x in $Cam){Copy-Item $x (Join-Path $Dir ([IO.Path]::GetFileName($x))) -Force}
Write-Host 'Step 5/8 - Verifying local AI...';$tags=Invoke-RestMethod 'http://127.0.0.1:11434/api/tags';$names=@($tags.models|%{if($_.name){$_.name}else{$_.model}});if(-not($names -contains 'qwen3:1.7b')){& ollama pull qwen3:1.7b;if($LASTEXITCODE -ne 0){throw 'qwen3:1.7b unavailable'}}
Write-Host 'Step 6/8 - Installing V15 and restarting bridge...';Copy-Item $candidate $App -Force;Stop-B;Start-Sleep -Milliseconds 700;Start-B;Start-Sleep -Seconds 3;& tailscale serve --bg http://127.0.0.1:8765|Out-Host
Write-Host 'Step 7/8 - Smoke tests...';try{$h=Invoke-WebRequest 'http://127.0.0.1:8765/health' -UseBasicParsing -TimeoutSec 15;if($h.StatusCode-ne200){throw 'Bridge failed'};$p=Invoke-WebRequest 'http://127.0.0.1:8765/' -UseBasicParsing -TimeoutSec 15;foreach($m in @('V15 PRODUCT STUDIO','Platform Health','Backup & Restore','Quick Create','Batch Prompt Builder','Continuity Matrix','Environment Vault','Prompt Library')){if(-not$p.Content.Contains($m)){throw "Served page missing $m"}};$o=Invoke-WebRequest 'http://127.0.0.1:8765/ollama/api/tags' -UseBasicParsing -TimeoutSec 20;if($o.StatusCode-ne200){throw 'Ollama proxy failed'}}catch{Write-Host 'Smoke test failed; restoring previous page.' -ForegroundColor Yellow;Stop-B;if(Test-Path $Backup){Copy-Item $Backup $App -Force};Start-B;throw}
Write-Host 'Step 8/8 - Private HTTPS check...';try{$r=Invoke-WebRequest ($PrivateUrl+'?v=1500') -UseBasicParsing -TimeoutSec 25;if($r.StatusCode-ne200-or-not$r.Content.Contains('V15 PRODUCT STUDIO')){throw 'V15 HTTPS check failed'};Write-Host 'Private HTTPS PASS.' -ForegroundColor Green}catch{Write-Warning $_.Exception.Message}
Write-Host '';Write-Host 'V15 PRODUCT STUDIO IS READY' -ForegroundColor Green;Write-Host ($PrivateUrl+'?v=1500') -ForegroundColor Cyan;Write-Host 'Dashboard + Quick Create + Platform Health + Full text-only Backup/Restore.';Write-Host 'All V14.8 creative production features remain installed.';Write-Host 'Always-On watchdog remains compatible.';Start-Process ($PrivateUrl+'?v=1500')